using ElectroComApi.DTO;
using ElectroComApi.Models;
using ElectroComApi.Repo;
using ElectroComApi.Data;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System.Linq;
using AutoMapper;

namespace ElectroComApi.Services
{
    public interface IQuotationService
    {
        Task<QuotationResponseDto> ProcessQuotationRequestAsync(QuotationRequestDto requestDto);
        Task<OrderConfirmationDto> ConfirmOrderAsync(QuotationResponseDto responseDto);
        Task<QuotationResponseDto> GetQuotationResponseAsync(int requestId);
    }

    public class QuotationService : IQuotationService
    {
        private readonly IQuotationRequestRepo _requestRepo;
        private readonly IQuotationResponseRepo _responseRepo;
        private readonly IProductQuoteInfoRepo _productQuoteInfoRepo;
        private readonly ApplicationDbContext _context;
        private readonly IInventoryService _inventoryService;
        private readonly IMapper _mapper;

        public QuotationService(IQuotationRequestRepo requestRepo, IQuotationResponseRepo responseRepo,
            IProductQuoteInfoRepo productQuoteInfoRepo, ApplicationDbContext context,
            IInventoryService inventoryService, IMapper mapper)
        {
            _requestRepo = requestRepo ?? throw new ArgumentNullException(nameof(requestRepo));
            _responseRepo = responseRepo ?? throw new ArgumentNullException(nameof(responseRepo));
            _productQuoteInfoRepo = productQuoteInfoRepo ?? throw new ArgumentNullException(nameof(productQuoteInfoRepo));
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _inventoryService = inventoryService ?? throw new ArgumentNullException(nameof(inventoryService));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        public async Task<QuotationResponseDto> ProcessQuotationRequestAsync(QuotationRequestDto requestDto)
        {
            if (requestDto == null || !requestDto.ProductRequests.Any())
                throw new ArgumentException("Invalid or empty quotation request.", nameof(requestDto));

            var request = _mapper.Map<QuotationRequest>(requestDto);

            // Set only the navigation property, not the FK
            var productRequestInfos = requestDto.ProductRequests.Select(pr => new ProductRequestInfo
            {
                ProductId = pr.ProductId,
                Quantity = pr.Quantity,
                QuotationRequest = request // Set navigation property
            }).ToList();

            request.ProductRequestInfos = productRequestInfos;
            await _requestRepo.SaveAsync(request); // Save QuotationRequest with children; EF will handle FKs

            var response = new QuotationResponse
            {
                RequestId = request.RequestId,
                ResponseDate = DateTime.UtcNow
            };
            await _responseRepo.SaveAsync(response); // Save first to get response.Id

            // Now create ProductQuoteInfo with correct QuotationResponseId
            var productQuoteInfos = requestDto.ProductRequests.Select(pr => new ProductQuoteInfo
            {
                QuotationResponseId = response.Id, // Set after response is saved
                ProductId = pr.ProductId,
                PricePerUnit = 100.00m + new Random().Next(10, 50),
                AvailableQuantity = _inventoryService.IsProductAvailable(pr.ProductId, pr.Quantity)
                    ? pr.Quantity + new Random().Next(0, 10)
                    : 0,
                EstimatedDeliveryDays = new Random().Next(2, 7)
            }).ToList();

            response.ProductQuoteInfos = productQuoteInfos;
            await _productQuoteInfoRepo.SaveAsync(productQuoteInfos);

            return _mapper.Map<QuotationResponseDto>(response);
        }

        public async Task<OrderConfirmationDto> ConfirmOrderAsync(QuotationResponseDto responseDto)
        {
            if (responseDto == null || !responseDto.ProductQuotes.Any())
                throw new ArgumentException("Invalid or empty quotation response.", nameof(responseDto));

            var orderConfirmation = new OrderConfirmation
            {
                // OrderId will be auto-generated by the database
                RequestId = responseDto.RequestId,
                ConfirmationDate = DateTime.UtcNow,
                Status = "Confirmed"
            };

            // Save orderConfirmation first to get its OrderId
            _context.OrderConfirmations.Add(orderConfirmation);
            await _context.SaveChangesAsync();

            var confirmedProducts = responseDto.ProductQuotes.Select(pq => new ConfirmedProduct
            {
                OrderConfirmationId = orderConfirmation.OrderId, // Use OrderId
                ProductId = pq.ProductId,
                QuantityConfirmed = pq.AvailableQuantity,
                Status = "Confirmed"
            }).ToList();

            orderConfirmation.ConfirmedProducts = confirmedProducts;
            _context.ConfirmedProducts.AddRange(confirmedProducts);
            await _context.SaveChangesAsync();

            return _mapper.Map<OrderConfirmationDto>(orderConfirmation);
        }

        public async Task<QuotationResponseDto> GetQuotationResponseAsync(int requestId)
        {
            var response = await _context.QuotationResponses
                .Include(q => q.ProductQuoteInfos)
                .FirstOrDefaultAsync(q => q.RequestId == requestId);
            if (response == null) return null;

            return _mapper.Map<QuotationResponseDto>(response);
        }
    }
}