// <auto-generated />
using System;
using GadgetHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GadgetHub.Migrations
{
    [DbContext(typeof(GadgetHubDbContext))]
    [Migration("20250731203350_CreateDistributorResponseTable")]
    partial class CreateDistributorResponseTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GadgetHub.Models.DistributorResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("DistributorResponses");
                });

            modelBuilder.Entity("GadgetHub.Models.FinalResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("FinalResponses");
                });

            modelBuilder.Entity("GadgetHub.Models.FullyComparedResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("FullyComparedResponses");
                });

            modelBuilder.Entity("GadgetHub.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GadgetHub.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "Logitech",
                            Category = "Peripherals",
                            Description = "Ergonomic wireless mouse with adjustable DPI.",
                            Name = "Wireless Mouse",
                            Url = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8"
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "Keychron",
                            Category = "Peripherals",
                            Description = "RGB backlit mechanical keyboard with blue switches.",
                            Name = "Mechanical Keyboard",
                            Url = "https://images.unsplash.com/photo-1519389950473-47ba0277781c"
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "Sony",
                            Category = "Accessories",
                            Description = "Over-ear headphones with active noise cancellation.",
                            Name = "Noise Cancelling Headphones",
                            Url = "https://images.unsplash.com/photo-1511367461989-f85a21fda167"
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "Dell",
                            Category = "Monitors",
                            Description = "27-inch 4K UHD monitor with HDR support.",
                            Name = "4K Monitor",
                            Url = "https://images.unsplash.com/photo-1519125323398-675f0ddb6308"
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "Anker",
                            Category = "Accessories",
                            Description = "Multiport USB-C hub with HDMI, USB 3.0, and SD card reader.",
                            Name = "USB-C Hub",
                            Url = "https://images.unsplash.com/photo-1465101046530-73398c7f28ca"
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "Samsung",
                            Category = "Storage",
                            Description = "1TB portable SSD with USB 3.2 Gen 2 support.",
                            Name = "Portable SSD",
                            Url = "https://images.unsplash.com/photo-1518770660439-4636190af475"
                        },
                        new
                        {
                            ProductId = 7,
                            Brand = "Apple",
                            Category = "Wearables",
                            Description = "Fitness tracking smartwatch with heart rate monitor.",
                            Name = "Smartwatch",
                            Url = "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b"
                        },
                        new
                        {
                            ProductId = 8,
                            Brand = "JBL",
                            Category = "Audio",
                            Description = "Waterproof Bluetooth speaker with 12-hour battery life.",
                            Name = "Bluetooth Speaker",
                            Url = "https://images.unsplash.com/photo-1509395176047-4a66953fd231"
                        },
                        new
                        {
                            ProductId = 9,
                            Brand = "Logitech",
                            Category = "Peripherals",
                            Description = "1080p HD webcam with built-in microphone.",
                            Name = "Webcam",
                            Url = "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2"
                        },
                        new
                        {
                            ProductId = 10,
                            Brand = "Belkin",
                            Category = "Accessories",
                            Description = "Fast wireless charging pad for smartphones.",
                            Name = "Wireless Charger",
                            Url = "https://images.unsplash.com/photo-1512446733611-9099a758e082"
                        });
                });

            modelBuilder.Entity("GadgetHub.Models.ProductDistributorMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ElectroComId")
                        .HasColumnType("int");

                    b.Property<int?>("GadgetCentralId")
                        .HasColumnType("int");

                    b.Property<int>("GadgetHubId")
                        .HasColumnType("int");

                    b.Property<int?>("TechWorldId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GadgetHubId");

                    b.ToTable("ProductDistributorMaps");
                });

            modelBuilder.Entity("GadgetHub.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GadgetHub.Models.DistributorResponse", b =>
                {
                    b.HasOne("GadgetHub.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GadgetHub.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GadgetHub.Models.FinalResponse", b =>
                {
                    b.HasOne("GadgetHub.Models.Order", "Order")
                        .WithMany("FinalResponses")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GadgetHub.Models.FullyComparedResponse", b =>
                {
                    b.HasOne("GadgetHub.Models.Order", "Order")
                        .WithMany("FullyComparedResponses")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GadgetHub.Models.Order", b =>
                {
                    b.HasOne("GadgetHub.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GadgetHub.Models.ProductDistributorMap", b =>
                {
                    b.HasOne("GadgetHub.Models.Product", "Product")
                        .WithMany("ProductDistributorMaps")
                        .HasForeignKey("GadgetHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GadgetHub.Models.Order", b =>
                {
                    b.Navigation("FinalResponses");

                    b.Navigation("FullyComparedResponses");
                });

            modelBuilder.Entity("GadgetHub.Models.Product", b =>
                {
                    b.Navigation("ProductDistributorMaps");
                });

            modelBuilder.Entity("GadgetHub.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
